env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/essential
  - plugin:prettier/recommended
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 12
  parser:
    js: 'espree'
  sourceType: module
plugins:
  - vue
rules:
  'no-console': 'off'
  'no-debugger': 'off'
  'vue/multi-word-component-names': 'off'
